### PR TITLE
fix: string regex :sob:

### PR DESCRIPTION
**Pull request by casz**

### CODE REVIEW

**Comment by casz** [comment]
:disappointed: https://github.com/jdalrymple/node-gitlab/commit/9e132f11713b352d037076bb35b70a0d2a053db2

**Comment by casz** [comment]
Well might burn 6.3.6 :fire:

**Comment by jdalrymple** [comment]
Tried to stop the build, but apparently that didnt work. Oh well, well push this soon :)

**Comment by casz** [comment]
The best way to stop a travis build is to push a newer commit, should kill the old build if you enable `Auto cancel branch builds`

**Comment by jdalrymple** [comment]
I think if it sees a newer commit it doesn't release anyways. Might of been just bad timing.

**Pull request merged**
