### PR TITLE
Remove non-standard Babel's plugins

### PR DESCRIPTION
**Pull request by r00ger**
In order to migrate to TypeScript, we have to get rid of non-standard language features

#89

### CODE REVIEW

**Comment by r00ger** [comment]
Typescript support stage3+ proposals

**Comment by r00ger** [comment]
They don't have plugins, features are being implemented in compiler itself, that's why they pick only standard features

**Comment by jdalrymple** [comment]
Ah, makes sense! Do you foresee that as a future problem? Where typescript lags behind such plugins? I dont know enough about the dev cycles of typescript :)

**Comment by r00ger** [comment]
About feature support — it neven was an issue to me (for more than two years). Frankly, I don't care about proposal (as the two I'm deleting), but when it comes to rather important features as spead/async/await/generators the lag isn't a problem, they release every two months

**Pull request merged**
