### PR TITLE
Dropped node version back to 8.9.0 while it is still in Maintenance LTS

### PR DESCRIPTION
**Pull request by bigkraig**
This came up in https://github.com/danger/danger-js/pull/855 where we are adding GitLab support to Danger JS. I didn't see any specific reason to drop support for 8.x which is still supported until Dec 2019.

### CODE REVIEW

**Comment by casz** [comment]
Please update Travis to build against 8.9.0 as well.

**Comment by bigkraig** [comment]
@casz any idea whats going on with travis? I am not very familiar with how to configure this but I assumed adding another version of node wouldn't create new jobs that also ran the integration tests like that.

**Comment by bigkraig** [comment]
@casz all set!!

**Comment by jdalrymple** [comment]
I'm going to check and see if we can move the two version tests into their respective stages. Not sure if it will work tbh, but if it doesnt, ill just revert it.

**Comment by casz** [comment]
@jdalrymple it is possible :)

Using matrix includes https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.travis.yml

**Comment by jdalrymple** [comment]
@casz That method gets rid of the stages though :(. I found this: https://github.com/travis-ci/travis-ci/issues/8295 ?

**Comment by jdalrymple** [comment]
So i added the modifications, but the integration tests seem to fail for 8.9.0. Not sure why exactly :s

**Comment by bigkraig** [comment]
> So i added the modifications, but the integration tests seem to fail for 8.9.0. Not sure why exactly :s

I think we just need to run the docker-compose as part of the 8.9.0 integration test, will know shortly.

**Comment by bigkraig** [comment]
@casz @jdalrymple all green! :+1:

**Comment by jdalrymple** [comment]
So the before_script part also had to be duplicated ? That's annoying lol. Looks good though! Ill merge and release tonight

**Comment by casz** [comment]
I think you can clean up the travis file even more :sweat_smile: Let me try it out.

**Comment by casz** [comment]
Nope :cry:

**Comment by jdalrymple** [comment]
Had my hopes up there for a moment @casz

**Comment by casz** [comment]
So did I :disappointed:

**Pull request merged**
