### PR TITLE
Simplify travis

### PR DESCRIPTION
**Pull request by casz**
Stages are just a fancy word for a script line :rofl: 

Magic number #300

### CODE REVIEW

**Comment by casz** [comment]
A build is currently running here: https://travis-ci.com/casz/node-gitlab/builds/107740583

**Comment by jdalrymple** [comment]
The only downside is the decreased clarity in the ci pipeline. The benefit to stages is that it becomes very clear what is running , and what failed

**Comment by casz** [comment]
I had hoped for more delay before reaching integration test hoping it would be alive :cry:

**Comment by jdalrymple** [comment]
Yea I tried in the past to use the liveliness check on the docker image, but couldn't get it to work

**Comment by casz** [comment]
True but Travis does a good job of collapsing the script lines

**Pull request closed without merging**
