### PR TITLE
Fix type definitions

### PR DESCRIPTION
**Pull request by DanielRose**
Fixes the Typescript type definitions as described in issue #329

### CODE REVIEW

**Comment by casz** [comment]
@DanielRose https://travis-ci.org/jdalrymple/node-gitlab/jobs/544715067 :sweat: 
So far it looks good if this fixes the types I happy :rabbit2:

**Comment by DanielRose** [comment]
@casz Forgot to run the linter... Now this should be correct (and uses semantic commit messages as well).

**Comment by jdalrymple** [comment]
Good to be merged?

**Pull request merged**
