### PR TITLE
Fix: camel_case POST params in MergeRequests.create

### PR DESCRIPTION
**Pull request by thoughtspile**
Creating a branch fails with `'source_branch is missing, target_branch is missing'`

---
This change is [Reviewable](https://reviewable.io/reviews/jdalrymple/node-gitlab/181)

### CODE REVIEW

**Comment by thoughtspile** [comment]
You might also want to check the other files for similar errors

**Comment by jdalrymple** [comment]
Hmm, this shouldnt happen since the params are snake cased always. Something is missing, ill look

**Comment by jdalrymple** [comment]
Found it

**Comment by jdalrymple** [comment]
I really should add tests to verify these things

**Comment by jdalrymple** [comment]
Push, should be released soon!

**Comment by thoughtspile** [comment]
Oh, now I see how it's supposed to work! Neat.

**Comment by jdalrymple** [comment]
It was just a convenience functionality so people could use whatever casing they wanted

**Pull request closed without merging**
