### PR TITLE
docs: Enabled declaration (.d.ts) files for dist

### PR DESCRIPTION
**Pull request by icanhasjonas**
I think this pull-request will improve the quality of life for typescript consumers.

It basically just enables type declarations to be generated.

### CODE REVIEW

**Comment by icanhasjonas** [comment]
... until #216 is merged at least

**Comment by icanhasjonas** [comment]
Thanks, @jdalrymple - any chance you can push a new release?

(I know, it's a cheesy update, but who doesn't like cheese?)

**Comment by jdalrymple** [comment]
Yea one min!

**Pull request merged**
