### PR TITLE
fix: include all modules for the browser bundle - closes #475

### LINKED ISSUE #475: `t is undefined` error thrown in Firefox when importing
**Description**
I will admit I am a beginner to js/node and it is likely that I am doing something wrong, however I cannot find a solution. I am using the API inside javascript in my website. I installed the package using `npm`, and can successfully link to the package like so:
```
<script src="/node_modules/gitlab/dist/index.browser.js"></script>
```
However, Firefox reports this in the developer javascript console:
```
TypeError: t is undefined                             index.browser.js:1:65052
```

**Steps to reproduce**
1. Run `npm install gitlab`
2. Link to the `index.browser.js` file in an `html` file
3. Check developer console to see error

**Expected behaviour**
It is expected to not see the syntax error.

**Actual behaviour**
The syntax error is thrown and renders the package unusable.

**Possible fixes**
Not sure.

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR produces a full browser bundle including all dependencies.

This also closes #475.

### CODE REVIEW

**Comment by jdalrymple** [comment]
Rollup crashes on the build step :/

**Comment by DanielRuf** [comment]
See the other PR ;-)

**Comment by DanielRuf** [comment]
I have pushed another PR which will trigger a working CI build. But these packages are not really actively maintained anymore and should be replaced.

**Comment by jdalrymple** [comment]
Not exactly sure what the purpose of this change is. When rollup +typescript compile the ts file, it handles commonjs modules?

**Comment by DanielRuf** [comment]
See https://github.com/jdalrymple/node-gitlab/issues/475 and what `externals` does. You do not actually bundle the dependencies for browsers.

This PR fixes this. Otherwise `universal-url` is undefined / not set.

You can beautify and decompress the output using the terser config to see the actual error.

**Comment by jdalrymple** [comment]
Thanks for the further explanation :)

**Pull request merged**
