### PR TITLE
WIP: Add group hooks for EE

### PR DESCRIPTION
**Pull request by casz**
Haven't tested yet, and group hooks are not documented in gitlab EE (only that EE has group webhooks) but dammit if it is not in the REST api... RIP...

### CODE REVIEW

**Comment by casz** [comment]
I do, just need to get into the office tomorrow 🙄

**Comment by casz** [comment]
I created: https://gitlab.com/gitlab-org/gitlab-ee/issues/7551

**Comment by casz** [comment]
Well, my suspicious was correct. It is not even in the REST API...

**Comment by jdalrymple** [comment]
Made it a WIP until Gitlab supports it

**Comment by casz** [comment]
Created a support ticket with GitLab since I was unsuccessful in creating a MR for the feature in the gitlab-ee repo 😭

**Comment by casz** [comment]
Closing I can always reopen when Gitlab if ever decides to add support

**Pull request closed without merging**
