### PR TITLE
Adding the ability to add `sudo` to specific requests

### PR DESCRIPTION
**Pull request by jdalrymple**
## Summary

```javascript
const { NotificationSettings } = new Gitlab({
  url:   'http://example.com', // Defaults to http://gitlab.com
  token: 'abcdefghij123456' // Can be created in your profile
}) ;

await NotificationSettings.edit({
  level: NotificationSettings.LEVELS.DISABLED
  sudo: 8,
})
```

### CODE REVIEW

**Comment by jdalrymple** [comment]
This will be added once #98 is finished

**Comment by casz** [comment]
Cleaner diff with the current base branch https://github.com/jdalrymple/node-gitlab/compare/remove-dependency-on-fs...specific-sudo

**Comment by jdalrymple** [comment]
Probably not for another week or so? Depends on how much progress i make on the other issue :)

**Comment by Musinux** [comment]
Okay, thanks !

**Pull request merged**
