### PR TITLE
Add /projects/:id/repository/commits/:sha/merge_requests endpoint

### PR DESCRIPTION
**Pull request by seb0uil**
Hi,

It seems /projects/:id/repository/commits/:sha/merge_requests enpoint does not exist in Commits API

I simply added it this way

### CODE REVIEW

**Comment by casz** [comment]
it included in `next` on npm @BruceHubbard

**Comment by BruceHubbard** [comment]
I just pulled down `gitlab@next` which resolved to `gitlab@5.0.0-rc.7` and it doesn't have this change

**Comment by jdalrymple** [comment]
Sorry for the delay! I'll release today. I just moved and have been lacking wifi lol

**Comment by jdalrymple** [comment]
Should be available in the latest next release

**Comment by BruceHubbard** [comment]
Awesome, thanks @jdalrymple!

**Pull request merged**
