### PR TITLE
Typescript Support

### PR DESCRIPTION
**Pull request by jdalrymple**

### CODE REVIEW

**Comment by casz** [comment]
A few conflicts that need to be resolved 😅

**Comment by jdalrymple** [comment]
@casz :joy: yea, ill get to those today

**Comment by casz** [comment]
Just being captain obvious 😂

**Comment by casz** [comment]
Seems this was merged in: https://github.com/jdalrymple/node-gitlab/commit/31132ce0d22854e9d313af7acc6b9678ee980c9d

**Comment by jdalrymple** [comment]
Yea running the tests now

**Comment by jdalrymple** [comment]
Just realized i merged this incorrectly, fixing that now

**Comment by casz** [comment]
🥇

**Comment by josh64x2** [comment]
@jdalrymple It looks like the typings aren't included in the dist? `"declaration": true` needs to be set in the `tsconfig.dist.json` and then the `types` key should be set in `package.json`. It would be great to use this library from within other typescript projects.

**Comment by casz** [comment]
@josh64x2 https://github.com/jdalrymple/node-gitlab/issues/137#issuecomment-417200110

**Comment by josh64x2** [comment]
@casz ahhh thanks :D

**Pull request merged**
