### PR TITLE
Fix: epic issues http methods were wrong

### PR DESCRIPTION
**Pull request by arsdehnel**
Not sure why these were `put/del` instead of `post/put` but these aren't working right now, this should fix that problem.

### CODE REVIEW

**Comment by jdalrymple** [comment]
I probably read the wrong endpoint smh. Thanks!

**Comment by arsdehnel** [comment]
Do you know when this might get tagged?  I've got a project I'm working on and would like to just keep using this one rather than having to go through and publish my own fork to our private npm registry and stuff.

**Comment by jdalrymple** [comment]
Didnt notice the missing keyword from the commit message. Ill fix this today :)

**Comment by arsdehnel** [comment]
My bad.  What's the keyword I need to include?  Maybe I missed something in the docs?

**Comment by jdalrymple** [comment]
It's not your fault :) I dont mentioned it anywhere, it has to do with semantic release. To trigger the builds, each commit must be prefixed with the type of change it was. So for this example, "fix: Epic issues http methods were wrong", which is what you named the PR (which is good) but it needs to be on the commit to trigger the build.

**Comment by jdalrymple** [comment]
Should be released soon :)

**Pull request merged**
