### PR TITLE
WIP: Initial docs for Projects service

### PR DESCRIPTION
**Pull request by beaverusiv**
This is a test to add docs to the repository. Taken on [the suggestion of Vuepress](https://github.com/jdalrymple/node-gitlab/issues/39#issuecomment-402535385), running `npm run docs:dev` will start a server which serves the formatted docs.

I do not have any opinion on how the docs get published or how they look, I merely want to get the content into markdown files so it can happen.

### CODE REVIEW

**Comment by beaverusiv** [comment]
Ok, I'll take this as confirmation to proceed. I will prioritise the documentation first as that provides the best value-add for users.

**Comment by beaverusiv** [comment]
Update: finished `Projects`, started `Groups`.

We need a nicer `docs/README.md` if someone has ideas? I think even if it's jst a small paragraph above a list of the documented services.

**Comment by jdalrymple** [comment]
I can merge this PR rn in the meantime?

**Comment by jdalrymple** [comment]
https://itnext.io/publish-a-vuepress-site-on-github-pages-with-travis-82036243bf36 This would be cool! On release it published the docs to a github page?

**Comment by beaverusiv** [comment]
I'll clean up the conflict and look at the publishing tonight so you can merge

**Comment by jdalrymple** [comment]
I can help rebase this at the end of the week

**Comment by beaverusiv** [comment]
Real life has got in the way so I won't realistically be able to finish this work. Do with what I've done as you want. Good luck!

**Comment by jdalrymple** [comment]
Thank you for the work!

**Comment by jdalrymple** [comment]
Going to try and rebase this at some point this week

**Pull request closed without merging**
